
# Mod Loader Properties | https://modmuss50.me/fabric.html
minecraft_version=26.3
# List oldest to newest, comma seperated.
supported_minecraft_versions=26.3
enabled_platforms=fabric,neoforge

fabric_loader_version=0.19.5
fabric_version=0.152.0+26.3

neoforge_version=26.3.0.7-beta
neoforge_loader_version_range=[2.0,)
neoforge_compatibility_range=[26.3,)

# Mod Properties
mod_version = 2.7.0
maven_group = me.cg360
archives_base_name = BridgingMod

# Compilation settings
org.gradle.jvmargs=-Xmx3G
show_dev_warnings=false
# sable is ahead of architectury so:
loom.ignoreDependencyLoomVersionValidation=true

# Dependencies
kotlin_for_forge=6.2.0
modmenu_version=21.0.0-beta.1
yacl_version=3.9.7+26.3

# Compatibility Dependencies
dynamiccrosshair_version=9.15
dynamiccrosshair_version_artifact=9.15+26.3

dank_storage_file_id=7853310

sable_companion_version=1.21.1:1.6.0


## Publishing configuration
debug_publishing=false
release_type=release

curseforge_project=533942