
# Mod Loader Properties | https://modmuss50.me/fabric.html
minecraft_version=26.2
# List oldest to newest, comma seperated.
supported_minecraft_versions=26.2
enabled_platforms=fabric,neoforge

fabric_loader_version=0.19.3
fabric_version=0.152.0+26.2

neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[2.0,)
neoforge_compatibility_range=[26.2,)

# Mod Properties
mod_version = 2.7.0
maven_group = me.cg360
archives_base_name = BridgingMod

# Compilation settings
org.gradle.jvmargs=-Xmx3G
show_dev_warnings=false
# sable is ahead of architectury so:
loom.ignoreDependencyLoomVersionValidation=true

# Dependencies
kotlin_for_forge=6.2.0
modmenu_version=20.0.0-alpha.1
yacl_version=3.9.4+26.2

# Compatibility Dependencies
dynamiccrosshair_version=9.12
dynamiccrosshair_version_artifact=9.12+26.1

dank_storage_file_id=7853310

#----------------------
# the following are *broken* - with remapping, these need updating to 26.1 to compile.
# Make sure on update:
# [ ] compatibility classes are renamed from .java.old -> .java
# [ ] inits in fabric & neoforge base classes are updated
# [ ] dependencies in fabric.mod.json & neoforge.mod.toml are readded
# [ ] dynamic crosshair entrypoint is readded to fabric.mod.json
# [ ] dependencies in build.gradle are updated.

#bank_storage_file_id=LC7UDnPb
#----------------------

sable_companion_version=1.21.1:1.6.0


## Publishing configuration
debug_publishing=false
release_type=release

curseforge_project=533942