
# Mod Loader Properties | https://modmuss50.me/fabric.html
minecraft_version=26.1
# List oldest to newest, comma seperated.
supported_minecraft_versions=26.1
enabled_platforms=fabric,neoforge

fabric_loader_version=0.18.5
fabric_version=0.144.3+26.1

neoforge_version=26.1.0.15-beta
neoforge_loader_version_range=[2.0,)
neoforge_compatibility_range=[26.1,)

# Mod Properties
mod_version = 2.6.5
maven_group = me.cg360
archives_base_name = BridgingMod

# Compilation settings
org.gradle.jvmargs=-Xmx3G
show_dev_warnings=false

# Dependencies
kotlin_for_forge=6.0.0
modmenu_version=18.0.0-alpha.8
yacl_version=3.9.1+26.1

# Compatibility Dependencies
# these are *broken* - with remapping, these need updating to 26.1 to compile.
# Make sure on update:
# [ ] compatibility classes are renamed from .java.old -> .java
# [ ] inits in fabric & neoforge base classes are updated
# [ ] dependencies in fabric.mod.json & neoforge.mod.toml are readded
# [ ] dynamic crosshair entrypoint is readded to fabric.mod.json
# [ ] dependencies in build.gradle are updated.

#dynamiccrosshair_version=9.11
#dynamiccrosshair_version_artifact=9.5+1.21.6
# this is broken ^
# the classifiers on newly published api jars is broken. It should be at the beginning of the artifact version,
# but it's at the end. This changed for 9.6+ and now I can't find a way
# to get gradle to find it.

#dank_storage_file_id=6060949
#bank_storage_file_id=LC7UDnPb

## Publishing configuration
debug_publishing=false
release_type=release

curseforge_project=533942