architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/bridgingmod.accesswidener")
}

dependencies {
    // Don't remove - used for @Environment annotations and nothing else.
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    api "dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric"

    compileOnly("maven.modrinth:dynamiccrosshair:${rootProject.dynamiccrosshair_version_artifact}-fabric:api")
    api("dev.ryanhcode.sable-companion:sable-companion-common-${rootProject.sable_companion_version}")

    // optional compat
    compileOnly("curse.maven:dankstorage-335673:${rootProject.dank_storage_file_id}")
    //compileOnly("maven.modrinth:bank-storage:${rootProject.bank_storage_file_id}") //todo: re-enable when updated to 26.1
}
