architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/bridgingmod.accesswidener")
}

dependencies {
    // Don't remove - used for @Environment annotations and nothing else.
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    modApi "dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric"

    modCompileOnly("maven.modrinth:dynamiccrosshair:${rootProject.dynamiccrosshair_version_artifact}-fabric:api")

    // optional compat
    modCompileOnly("curse.maven:dankstorage-335673:${rootProject.dank_storage_file_id}")
    modCompileOnly("maven.modrinth:bank-storage:${rootProject.bank_storage_file_id}")
    modCompileOnly("curse.maven:building-wands-363392:${rootProject.building_wands_file_id}")
}
